onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_one_mac_gemm/M_i
add wave -noupdate /tb_one_mac_gemm/K_i
add wave -noupdate /tb_one_mac_gemm/N_i
add wave -noupdate /tb_one_mac_gemm/clk_i
add wave -noupdate /tb_one_mac_gemm/rst_ni
add wave -noupdate /tb_one_mac_gemm/start
add wave -noupdate /tb_one_mac_gemm/done
add wave -noupdate /tb_one_mac_gemm/test_depth
add wave -noupdate /tb_one_mac_gemm/sram_a_addr
add wave -noupdate /tb_one_mac_gemm/sram_b_addr
add wave -noupdate /tb_one_mac_gemm/sram_c_addr
add wave -noupdate /tb_one_mac_gemm/K_packed_depth
add wave -noupdate /tb_one_mac_gemm/N_packed_depth
add wave -noupdate /tb_one_mac_gemm/M_packed_depth
add wave -noupdate /tb_one_mac_gemm/global_m
add wave -noupdate /tb_one_mac_gemm/global_n
add wave -noupdate /tb_one_mac_gemm/global_k
add wave -noupdate /tb_one_mac_gemm/temp_row_pack_data
add wave -noupdate /tb_one_mac_gemm/temp_col_pack_data
add wave -noupdate /tb_one_mac_gemm/val
add wave -noupdate /tb_one_mac_gemm/sram_a_rdata
add wave -noupdate /tb_one_mac_gemm/sram_b_rdata
add wave -noupdate /tb_one_mac_gemm/sram_c_wdata
add wave -noupdate /tb_one_mac_gemm/sram_c_we
add wave -noupdate /tb_one_mac_gemm/time_delay/delay
add wave -noupdate /tb_one_mac_gemm/clk_delay/delay
add wave -noupdate /tb_one_mac_gemm/i_sram_a/clk_i
add wave -noupdate /tb_one_mac_gemm/i_sram_a/rst_ni
add wave -noupdate /tb_one_mac_gemm/i_sram_a/mem_addr_i
add wave -noupdate /tb_one_mac_gemm/i_sram_a/mem_we_i
add wave -noupdate /tb_one_mac_gemm/i_sram_a/mem_wr_data_i
add wave -noupdate /tb_one_mac_gemm/i_sram_a/mem_rd_data_o
add wave -noupdate /tb_one_mac_gemm/i_sram_b/clk_i
add wave -noupdate /tb_one_mac_gemm/i_sram_b/rst_ni
add wave -noupdate /tb_one_mac_gemm/i_sram_b/mem_addr_i
add wave -noupdate /tb_one_mac_gemm/i_sram_b/mem_we_i
add wave -noupdate /tb_one_mac_gemm/i_sram_b/mem_wr_data_i
add wave -noupdate /tb_one_mac_gemm/i_sram_b/mem_rd_data_o
add wave -noupdate /tb_one_mac_gemm/i_sram_c/clk_i
add wave -noupdate /tb_one_mac_gemm/i_sram_c/rst_ni
add wave -noupdate /tb_one_mac_gemm/i_sram_c/mem_addr_i
add wave -noupdate /tb_one_mac_gemm/i_sram_c/mem_we_i
add wave -noupdate /tb_one_mac_gemm/i_sram_c/mem_wr_data_i
add wave -noupdate /tb_one_mac_gemm/i_sram_c/mem_rd_data_o
add wave -noupdate /tb_one_mac_gemm/i_dut/clk_i
add wave -noupdate /tb_one_mac_gemm/i_dut/rst_ni
add wave -noupdate /tb_one_mac_gemm/i_dut/start_i
add wave -noupdate /tb_one_mac_gemm/i_dut/M_size_i
add wave -noupdate /tb_one_mac_gemm/i_dut/K_size_i
add wave -noupdate /tb_one_mac_gemm/i_dut/N_size_i
add wave -noupdate /tb_one_mac_gemm/i_dut/sram_a_addr_o
add wave -noupdate /tb_one_mac_gemm/i_dut/sram_b_addr_o
add wave -noupdate /tb_one_mac_gemm/i_dut/sram_c_addr_o
add wave -noupdate /tb_one_mac_gemm/i_dut/sram_a_rdata_i
add wave -noupdate /tb_one_mac_gemm/i_dut/sram_b_rdata_i
add wave -noupdate /tb_one_mac_gemm/i_dut/sram_c_wdata_o
add wave -noupdate /tb_one_mac_gemm/i_dut/sram_c_we_o
add wave -noupdate /tb_one_mac_gemm/i_dut/done_o
add wave -noupdate /tb_one_mac_gemm/i_dut/M_count
add wave -noupdate /tb_one_mac_gemm/i_dut/K_count
add wave -noupdate /tb_one_mac_gemm/i_dut/N_count
add wave -noupdate /tb_one_mac_gemm/i_dut/busy
add wave -noupdate /tb_one_mac_gemm/i_dut/valid_data
add wave -noupdate /tb_one_mac_gemm/i_dut/K_packed_depth
add wave -noupdate /tb_one_mac_gemm/i_dut/N_packed_depth
add wave -noupdate /tb_one_mac_gemm/i_dut/M_packed_depth
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[3]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[3]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[3]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[3]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[3]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[3]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[3]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[3]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[3]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[3]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[3]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[2]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[2]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[2]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[2]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[2]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[2]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[2]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[2]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[2]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[2]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[2]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[1]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[1]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[1]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[1]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[1]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[1]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[1]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[1]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[1]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[1]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[1]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[0]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[0]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[0]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[0]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[0]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[0]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[0]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[0]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[0]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[0]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[3]/gem_mac_pe_n[0]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[3]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[3]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[3]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[3]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[3]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[3]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[3]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[3]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[3]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[3]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[3]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[2]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[2]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[2]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[2]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[2]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[2]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[2]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[2]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[2]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[2]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[2]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[1]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[1]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[1]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[1]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[1]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[1]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[1]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[1]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[1]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[1]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[1]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[0]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[0]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[0]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[0]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[0]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[0]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[0]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[0]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[0]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[0]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[2]/gem_mac_pe_n[0]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[3]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[3]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[3]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[3]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[3]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[3]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[3]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[3]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[3]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[3]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[3]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[2]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[2]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[2]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[2]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[2]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[2]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[2]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[2]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[2]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[2]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[2]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[1]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[1]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[1]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[1]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[1]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[1]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[1]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[1]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[1]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[1]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[1]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[0]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[0]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[0]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[0]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[0]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[0]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[0]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[0]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[0]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[0]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[1]/gem_mac_pe_n[0]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[3]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[3]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[3]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[3]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[3]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[3]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[3]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[3]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[3]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[3]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[3]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[2]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[2]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[2]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[2]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[2]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[2]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[2]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[2]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[2]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[2]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[2]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[1]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[1]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[1]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[1]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[1]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[1]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[1]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[1]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[1]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[1]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[1]/i_mac_pe/mult_result}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[0]/i_mac_pe/clk_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[0]/i_mac_pe/rst_ni}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[0]/i_mac_pe/a_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[0]/i_mac_pe/b_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[0]/i_mac_pe/a_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[0]/i_mac_pe/b_valid_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[0]/i_mac_pe/init_save_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[0]/i_mac_pe/acc_clr_i}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[0]/i_mac_pe/c_o}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[0]/i_mac_pe/acc_valid}
add wave -noupdate {/tb_one_mac_gemm/i_dut/gem_mac_pe_m[0]/gem_mac_pe_n[0]/i_mac_pe/mult_result}
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/clk_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/rst_ni
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/start_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/input_valid_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/result_valid_o
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/busy_o
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/done_o
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/M_size_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/K_size_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/N_size_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/M_count_o
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/K_count_o
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/N_count_o
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/K_packed_depth
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/N_packed_depth
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/M_packed_depth
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/move_K_counter
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/move_N_counter
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/move_M_counter
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/move_counter
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/clear_counters
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/last_counter_last_value
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/current_state
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/next_state
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_K_counter/clk_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_K_counter/rst_ni
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_K_counter/tick_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_K_counter/clear_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_K_counter/ceiling_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_K_counter/count_o
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_K_counter/last_value_o
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_N_counter/clk_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_N_counter/rst_ni
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_N_counter/tick_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_N_counter/clear_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_N_counter/ceiling_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_N_counter/count_o
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_N_counter/last_value_o
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_M_counter/clk_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_M_counter/rst_ni
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_M_counter/tick_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_M_counter/clear_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_M_counter/ceiling_i
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_M_counter/count_o
add wave -noupdate /tb_one_mac_gemm/i_dut/i_gemm_controller/i_M_counter/last_value_o
add wave -noupdate /tb_one_mac_gemm/G_memory
add wave -noupdate -expand /tb_one_mac_gemm/i_sram_c/memory
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {94 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 137
configure wave -valuecolwidth 194
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {94 ns} {865 ns}
